grace-shopper-orgs/chai-noon

package-lock.json, script/seed.js, server/db/models/user.js
=> Model user

script/seed.js, server/db/models/cart.js
=> Models cart

package-lock.json, script/seed.js, server/db/models/index.js, server/db/models/product.js, server/db/models/product.spec.js
=> product model created

client/components/AllProducts.js, client/routes.js, client/store/index.js, client/store/products.js, script/seed.js, server/api/index.js, server/api/products.js, server/db/models/index.js
=> view_all_products

script/seed.js, server/db/models/cart.js, server/db/models/index.js
=> added cart seeding

client/components/SingleProduct.js, client/routes.js, client/store/index.js, client/store/singleProduct.js, server/api/index.js, server/api/products.js
=> Single project

client/components/auth-form.js, client/store/user.js, public/index.html, server/db/models/index.js
=> updated working routes for form login and logout

client/components/auth-form.js, client/store/user.js, server/api/gatekeeping.js, server/api/products.js
=> Is admin middleware

client/components/auth-form.js, client/store/user.js, server/api/products.js
=> fixed user auth thunks and seperated dispatch handling

client/components/AddProduct.js, client/components/AllProducts.js, client/components/SingleProduct.js, client/components/UpdateProduct.js, client/routes.js, client/store/products.js, client/store/singleProduct.js, script/seed.js, server/api/products.js, server/db/models/product.js
=> Product update delete

server/api/order.js
=> load products with order in api route

client/components/ErrorPage.js, script/seed.js, server/api/products.js, server/api/products.spec.js, server/api/users.spec.js, server/db/models/product.js, server/db/models/product.spec.js, server/db/models/user.spec.js
added test cases to different product routes & fixed old tests
---
=> Test routes

client/components/AddProduct.js, client/components/AllProducts.js, client/components/AllUsers.js, client/components/SingleProduct.js, client/routes.js, client/store/index.js, client/store/user.js, client/store/users.js, script/seed.js, server/api/products.js, server/api/users.js, server/auth/google.js
=> admin access restrictions

client/components/AllProducts.js, client/components/LoginSignUp_Form.js, client/components/WelcomePage.js, client/components/navbar.js, client/routes.js, public/style.css
=> connected all routes and added guest product view

client/components/AllProducts.js, client/components/navbar.js, client/routes.js, public/style.css
=> fixes to frontend routes

client/components/AllProducts.js, client/components/navbar.js, client/store/activeOrder.js, public/style.css
=> Single product form

client/components/ActiveOrder.js, client/components/WelcomePage.js, client/components/auth-form.js, client/store/activeOrder.js, client/store/user.js, server/api/order.js, server/api/products.js
=> merge local and db cart

client/components/AllProducts.js, client/components/Pagination.js, client/components/WelcomePage.js, public/style.css, server/api/order.js
=> Feature: pagination

client/components/ActiveOrder.js, client/components/AddProduct.js, client/components/AllProducts.js, client/components/AllUsers.js, client/components/CheckoutPage.js, client/components/ErrorPage.js, client/components/Footer.js, client/components/PurchaseForm.js, client/components/SingleProduct.js, client/components/UpdateProduct.js, client/components/WelcomePage.js, client/components/auth-form.js, client/store/checkout.js, client/store/index.js, public/style.css, server/api/order.js, server/db/models/user.js
=> Checkout page

public/style.css
=> fixed cart bubble

client/components/ActiveOrder.js, client/components/AllProducts.js, public/style.css, server/api/order.js
=> small fixes

client/components/ActiveOrder.js, client/components/auth-form.js, client/components/navbar.js, client/store/user.js, public/style.css, server/api/order.js, server/api/products.js
=> Merge cart

client/components/navbar.js, public/style.css
=> edit hamburger css

client/components/CheckoutPage.js, client/store/checkout.js, client/store/user.js
=> checkout guest user

client/components/ActiveOrder.js, client/components/AddProduct.js, client/components/AllProducts.js, client/components/AllUsers.js, client/components/CheckoutPage.js, client/components/ErrorPage.js, client/components/PurchaseForm.js, client/components/SingleProduct.js, client/components/ThankYouPage.js, client/components/UpdateProduct.js, client/components/WelcomePage.js, client/components/auth-form.js, client/routes.js, client/store/checkout.js, client/store/user.js, public/style.css
=> fixed footer path and added thank you confirmation

client/routes.js, client/store/activeOrder.js, client/store/user.js
=> Clean store

client/store/user.js, public/style.css
=> fixed redirect

client/components/AllProducts.js, client/components/AllProductsAdmin.js, client/components/AllProductsUsers.js, client/routes.js
=> spliting AllProducts
